### ISSUE TITLE
Output initial values for `es'

### ISSUE THREAD

**Issue by trnnick** [trnnick/TStools#10]
Can you add the `initial' and`initial.season' in the output list of the es function?

**Comment by config-i1** [comment]
They are provided in state vector. Do we really need to provide two more variables in the output?

**Comment by trnnick** [comment]
Would make things cleaner, as then you would not need to find how many are the initial and how many are the states. What do you think? Maybe there is a way to do that already that I am not seeing. 

Consider the case where you need to run a rolling origin without re-optimising, you would like to be able to input the seed and persistence vectors easily. The inputs are there, but not the outputs for the estimated model.

**Comment by config-i1** [comment]
The problem with initials is that we have two types of that: seasonal and non-seasonal. So it's not clear what exactly to return: vector of non-seasonal, vector of non-seasonal and seasonal, matrix containing a lot of duplicates of non-seasonal initials (first part of state vector)... Well, we could return two parameters: initial and initial.season - but IMO this makes things messy. Currently function returns 17 objects and it is already easy to loose yourself...
That is the reason, why I hesitate to add this thing in the output.

**Comment by trnnick** [comment]
I think the two output option would be the best. If the issue is that it returns far too many outputs then building a class object perhaps?

**Comment by config-i1** [comment]
Screw the whole thing! It is done! See the new update.

I hope I'll get to classes one day :)

**Comment by trnnick** [comment]
hahaha!
