### ISSUE TITLE
Model pool for `es'

### ISSUE THREAD

**Issue by trnnick** [trnnick/TStools#11]
A couple of suggestions on the model input. 
Should we replace X with C (to better connect with combination) and use X to restrict Z to only additive options?

**Comment by dmi3kno** [comment]
Agree with the "C" proposal. Another alternative would be to have a separate parameter: `ICcombine = c(FALSE. TRUE)` or in extreme case `output = c("best", "ICcombine", "all")` ;) 

With regards to using X to restrict Z, I think better solution would be based on a character vector of the model names, e.g.:
`modelnames <- c("AAA", "AAdA", "ANA",  "ANN"); fit <- es(model=modelnames, ...)`
You then need to check the length of this vector and run all models  `%in% unique(model)`.
This may be further away from standard `forecast` notation, but quite flexible.

**Comment by trnnick** [comment]
Good idea for the 'modelnames', should be relatively easy to implement both? I think a simple count of the input length should be sufficient.

**Comment by config-i1** [comment]
I will change the name to "C" if you really want it.

`modelnames` is not so hard to implement and IMO is a better solution than creating more and more different letters.

Next time... definitely :)

**Comment by config-i1** [comment]
Should we change `Z` to `S` as well? S - for "Selection".

**Comment by trnnick** [comment]
You have a point, but perhaps there is some merit in making it similar to the well known ets function. 
You lead this function, so it is up to you! If you go for 'S' then probably 'X' could be something else as well.

**Comment by dmi3kno** [comment]
I love `ZZZ`. Lets stick to it so long that Rob Hyndman has it in `ets()`. And your proposed `CCC` is just `ZZZ` with `ICcombine = TRUE` (or if you want to give respect to the man: `ICcombine="kolassa"`).

**Comment by config-i1** [comment]
Done.
"CCC" now stands for combinations and model now accepts vector of names.
- small speed increase
