### ISSUE TITLE
Data restrictions for es

### ISSUE THREAD

**Issue by trnnick** [trnnick/TStools#13]
When running seasonal models there is this:

if (Stype != "N" & (obs/datafreq) < 2) {
    message("Not enough observations for the seasonal model. Only non-seasonal models are available.")
    Stype <- "N"
}

If initial.season and initial are provided is this necessary? I cannot see why

**Comment by config-i1** [comment]
It is not, you are right. I just didn't bother to make a check there. Let me fix this.
