### ISSUE TITLE
Manual bounds for es

### ISSUE THREAD

**Issue by trnnick** [trnnick/TStools#14]
I think it might be helpful to add manual bounds for the smoothing parameters of es. 
Currently there are bounds=c("usual","admissible")
One may still want to restrict the search space further. Perhaps add one-two new inputs for manual min max bounds. These could be -inf +inf (or whatever) by default, but could then be restricted by the user to the desirable values. If that is a vector then in the cost function these can be passed as additional restrictions on top of the usual/admissible bounds.
I am in particularly interested in restricting phi further, but I can think of scenarios that this might be helpful for the other parameters. 

One alternative would be to pass these directly as the limits for the usual bounds, though this may not be as intuitive for the user. I am not in favour of this option. 

Also these is a typo on the bounds input at the es.Rd

**Comment by config-i1** [comment]
Will do as soon as I get my hands on it.

**Comment by config-i1** [comment]
Not relevant here anymore.
