### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by epslong** [trnnick/TStools#17]
Hi, 
I have tried several times to install the TStools package using the below command:
devtools::install_github("trnnick/TStools")

But have encountered below error:
- installing _source_ package 'TStools' ...
  *\* libs

**\* arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/R/R-33~1.1/include" -DNDEBUG    -I"C:/R/R-3.3.1/library/Rcpp/include" -I"C:/R/R-3.3.1/library/RcppArmadillo/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++: not found
make: **\* [RcppExports.o] Error 127
Warning: running command 'make -f "Makevars.win" -f "C:/R/R-33~1.1/etc/i386/Makeconf" -f "C:/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="TStools.dll" OBJECTS="RcppExports.o ssgeneralfun.o"' had status 2
ERROR: compilation failed for package 'TStools'
- removing 'C:/R/R-3.3.1/library/TStools'

Is there any known issues here? Thanks!

**Comment by config-i1** [comment]
Hi,
What I see from the output you have provided, is that you are missing g++ in your Rtools:

> > c:/Rtools/mingw_32/bin/g++: not found

I don't know why, this is strange. Can you, please, reinstall Rtools and try again?

**Comment by epslong** [comment]
Thanks! I just reinstalled Rtools, and now the error message is gone.
