### ISSUE TITLE
theta method shows error when straight line time series

### ISSUE THREAD

**Issue by xiesong** [trnnick/TStools#22]
Hello, thanks for the wonderful package. In the new version when we have straigh tline time series, theta method trows an error, this possible could how the theta method tests seasonality? Below is a reproducible example.

> tsa <- ts(rep(10,20),frequency = 4)
> theta(tsa)
Error in if (season.exist == TRUE) { : 
missing value where TRUE/FALSE needed

**Comment by trnnick** [comment]
Thanks for spotting this, can you please tell me how long is your time series and what is its frequency?
I was just pointed out that it is in the code! My mistake, I will investigate and get back to you

**Comment by trnnick** [comment]
FIxed! There is an issue with the built-in function friedman.test when the input is constant. Both theta and seasplot should now be fine.

**Comment by xiesong** [comment]
Thank you, please close the ticket.
