### ISSUE TITLE
Error installing the Lib

### ISSUE THREAD

**Issue by Guillermon13** [trnnick/TStools#24]
I have the following issue when i try to install the library

devtools::install_github("trnnick/TStools")
Downloading GitHub repo trnnick/TStools@master  
checking for file  'C:\Users\g.nebot.troyano\AppData\Local\Temp\Rtmps7vNDA\remotes5bc838c81319\trnnick-TStools-4912b2e/DESCRIPTION' ...
-  preparing 'TStools':
   checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'TStools_3.0.0.tar.gz'

Installing package into ‘C:/Users/g.nebot.troyano/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'TStools' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: object 'hm' is not exported by 'namespace:smooth'
Ejecución interrumpida
ERROR: lazy loading failed for package 'TStools'
* removing 'C:/Users/g.nebot.troyano/Documents/R/win-library/3.6/TStools'
Error: Failed to install 'TStools' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/GNEBOT~1.TRO/AppData/Local/Temp/Rtmps7vNDA/file5bc87a347db4/TStools_3.0.0.tar.gz’ had non-zero exit status

How can i fix it?
Thanks in advance!

**Comment by config-i1** [comment]
Hi,

Thanks for bringing this up!
This should be fixed now. Please, give it another try.

Cheers,
Ivan

**Comment by Guillermon13** [comment]
Thanks for you quick response!

Have a great day

Kind Regards
Guillermo
