### ISSUE TITLE
Introduce exogenous variables in ets2

### ISSUE THREAD

**Issue by config-i1** [trnnick/TStools#5]

**Comment by config-i1** [comment]
Finally done!

**Comment by trnnick** [comment]
Great stuff!

```
  From: Ivan Svetunkov <notifications@github.com>
```

 To: trnnick/TStools TStools@noreply.github.com 
 Sent: Sunday, 6 September 2015, 21:48
 Subject: Re: [TStools] Introduce exogenous variables in ets2 (#5)

Finally done!—
