### ISSUE TITLE
Rewrite sim.etc in Rcpp

### ISSUE THREAD

**Issue by config-i1** [trnnick/TStools#6]
It needs to be faster so it can be used for intervals construction in ets2.

**Comment by trnnick** [comment]
There is still a problem with the multiplicative components, if you are reimplementing it maybe a rethink of the logic is necessary, or simply an error trapment.

**Comment by config-i1** [comment]
Multiplicative models are pain in the ass!

I want to use lognormal distribution for the errors as a default and I will defenitely need to do something with the parameters restrictions.

The general rule here for now is to use lower values of standard deviation and smoothing parameters... Otherwise it just explodes.

**Comment by trnnick** [comment]
Would it make sense to simulate an additive model in logs and just take the exponent back?

**Comment by config-i1** [comment]
That's exactly what's happening for the pure multiplicative models. When it comes to the mixed models, it becomes a bit more complicated.
In general I would recommend to use alpha, beta, gamma close to 0.1 and standard deviation close to 0.05. Then the model simulates a meaningful series. Don't forget to use the right order: "mean=0, sd=0.05".

**Comment by trnnick** [comment]
Even with these you can end up having some series that are off. I have added a further error trapping to avoid meaningless results, where I ask for a replacement series. It may add some extra time in some instances, but it is one way to proceed and ensure appropriate output.

**Comment by config-i1** [comment]
Can you push your updates? I don't think that they are here...

**Comment by config-i1** [comment]
The new version of sim.ets() uses Rcpp.
