### ISSUE TITLE
Nemenyi Test Critical Difference

### ISSUE THREAD

**Issue by jennystone** [trnnick/TStools#8]
The literature specifies that
|Rank1 - Rank2| > CD
for Rank1 to be significantly better than Rank2
However the whiskers in the plots extend both sides making the equation
|Rank1 - Rank2| > 2CD
Can we include another plot option with 1 sided whisker?

**Comment by config-i1** [comment]
Hi!
Thanks for your comment!

But shouldn't it be two sided anyway?
We have this inequality:
|Rank1 - Rank2| > CD
which is equivalent to two inequalities:
1. Rank1 - Rank2 > CD
2. Rank1 - Rank2 < CD

Which leads to the lower and upper bounds and, as a result, to two whiskers.

Does it make sense?

**Comment by trnnick** [comment]
Slide 9 in the following presentation may be helpful on this:
http://kourentzes.com/forecasting/2012/04/19/statistical-significance-of-forecasting-methods-an-empirical-evaluation-of-the-robustness-and-interpretability-of-the-mcb-anom-and-friedman-nemenyi-test/

To the best of my knowledge the two-sidedness is already considered in the calculation of the critical distance.

**Comment by config-i1** [comment]
Looks like the issue is not what it seems.
